name: Deploy Resize (Angular)

on:
  push:
    branches: [ main ]
    paths:
      - 'resize/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Angular CLI
        run: npm install -g @angular/cli@latest

      - name: Install dependencies
        working-directory: ./resize
        run: npm install --legacy-peer-deps

      - name: Build
        working-directory: ./resize
        run: npm run build

      - name: Deploy to OVH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 37.187.218.143
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "resize/dist/resize/browser/**"
          target: /var/www/adrien-sheng-lin.fr/resize
          overwrite: true
          strip_components: 4
