name: Deploy Site Home (Static)

on:
  push:
    branches: [ main ]
    paths:
      - 'site-home/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to OVH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 37.187.218.143
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "site-home/*"
          target: /var/www/adrien-sheng-lin.fr/html
